# https://docs.docker.com/compose/
services:
  node-red:
    container_name: node-red
    # https://hub.docker.com/r/nodered/node-red/
    build: ../services/node-red/
    image: node-red
    restart: always
    volumes:
      - node-red_data:/data
    networks:
      - tfm-iabd-net
    ports:
      - 1880:1880
    depends_on:
      - "mongo"
  mongo:
    container_name: mongo-db
    # https://hub.docker.com/r/_/mongo/
    build: ../services/mongodb/
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
     - tfm-iabd-net
    command: ["--bind_ip_all"]
    ports:
      - "27017:27017"
volumes:
  node-red_data:
    driver: "local"
  mongodb_data:
    driver: "local"
networks:
  tfm-iabd-net: {}
  